#!/bin/bash

#$-l rt_F=1
#$ -l h_rt=168:00:00
#$-j y
#$-cwd
salloc --partition=project142-a100-v2 --ntasks=8 --ntasks-per-node=8 --gpus-per-node=8 --cpus-per-task=32 --time=60 --account=project142

source /etc/profile.d/modules.sh
module load singularity/3.5.3
module load openmpi/3.1.6
singularity run --nv /sample/container/NGC/tensorflow2/nvcr.io-nvidia-tensorflow.22.11-tf2-py3.sif

export OMPI_COMM_WORLD_RANK=0
export OMPI_COMM_WORLD_LOCAL_RANK=0
export OMPI_COMM_WORLD_SIZE=8

MODEL_FLAGS="--start_ema=0.999 --save_check_period=1000 --eval_interval=5000 --eval_fid=True --eval_similarity=False --check_dm_performance=False --compute_ema_fids=True --gan_fake_inner_type=model --gan_fake_outer_type=target_model_sg --gan_training=True --g_learning_period=2 --resume_checkpoint=/home/acf15618av/EighthArticleExperimentalResults/CIFAR10/resume_checkpoint/euler_edm_stop_grad_random_17_M_bs_384_from_edm_dsm_1.0/model050000.pt --microbatch=11"
python image_sample.py $MODEL_FLAGS --out_dir /home/fp084243/EighthArticleExperimentalResults/ImageNet64/author_CD/ --model_path=/home/fp084243/EighthArticleExperimentalResults/ImageNet64/author_ckpt/cd_imagenet64_lpips.pt --training_mode=cd --class_cond=True --eval_num_samples=250 --batch_size=250 --device_id=0 --sampler=exact --sampling_steps=1 --stochastic_seed=True --save_format=png --ind_1=5 --ind_2=3 --use_MPI=True

python fid_npzs.py --ref=/home/acf15618av/EighthArticleExperimentalResults/CIFAR10/author_ckpt/cifar10-32x32.npz --num_samples=50000 --images=/groups/gce50978/user/dongjun/EighthArticleExperimentalResults/CIFAR10/GAN/uncond/GAN_bs_264_ema_0.999/ctm_exact_sampler_1_steps_071000_itrs_0.999_ema_ --batch_size=500 --device=cuda:0
python fid_npzs.py --ref=/home/acf15618av/EighthArticleExperimentalResults/CIFAR10/author_ckpt/cifar10-32x32.npz --num_samples=50000 --images=/groups/gce50978/user/dongjun/EighthArticleExperimentalResults/CIFAR10/GAN/cond/GAN_bs_264/ctm_exact_sampler_35_steps_026000_itrs_0.999_ema_ --batch_size=500 --device=cuda:0
python fid_npzs.py --ref=/home/acf15618av/EighthArticleExperimentalResults/CIFAR10/author_ckpt/cifar10-32x32.npz --num_samples=50000 --images=/home/acf15618av/EighthArticleExperimentalResults/CIFAR10/resume_checkpoint/euler_edm_stop_grad_random_17_M_bs_384_from_edm_dsm_1.0/ --batch_size=500 --device=cuda:0
python fid_npzs.py --ref=/home/acf15618av/EighthArticleExperimentalResults/CIFAR10/author_ckpt/cifar10-32x32.npz --num_samples=50000 --images=/home/acf15618av/EighthArticleExperimentalResults/CIFAR10/EDM/edm_heun_sampler_8_steps_ond-vp_itrs_model_ema --batch_size=500 --device=cuda:2


python image_sample.py $MODEL_FLAGS --out_dir /home/fp084243/EighthArticleExperimentalResults/ImageNet64/aws-ckpt --model_path=/home/fp084243/EighthArticleExperimentalResults/ImageNet64/aws-ckpt/ema_0.999_009000.pt --class_cond=True --eval_num_samples=250 --batch_size=250 --device_id=0 --sampler=exact --sampling_steps=1 --stochastic_seed=True --save_format=png --ind_1=5 --ind_2=3 --use_MPI=True


scp abci:/groups/gce50978/user/dongjun/EighthArticleExperimentalResults/ImageNet64/fine_tune_ver2/M20_w1/model019000.pt /hdd/dongjun/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver2/M20_w1


MODEL_FLAGS="--attention_resolutions 32,16,8 --class_cond True --diffusion_steps 1000 --dropout 0.1 --image_size 64 --learn_sigma True --noise_schedule cosine --num_channels 192 --num_head_channels 64 --num_res_blocks 3 --resblock_updown True --use_new_attention_order True --use_fp16 True --use_scale_shift_norm True"
python classifier_sample.py $MODEL_FLAGS --classifier_scale 1.0 --classifier_path models/64x64_classifier.pt --classifier_depth 4 --model_path models/64x64_diffusion.pt $SAMPLE_FLAGS

docker exec -it ctm-cifar10-best bash
conda activate ctm
cd /home/ubuntu/EighthArticle/consistency_models-main_ver3
MODEL_FLAGS="--data_name=imagenet64 --class_cond=True --eval_interval=1000 --save_interval=1000 --num_classes=1000 --eval_batch=250 --eval_fid=True --eval_similarity=False --check_dm_performance=False --log_interval=100"
CKPT_FLAGS="--classifier_path=/home/ubuntu/EighthArticleExperimentalResults/ImageNet64/author_ckpt/64x64_classifier.pt --dm_sample_path_seed_42=/home/ubuntu/EighthArticleExperimentalResults/ImageNet64/DM/samples_ver2 --ref_path=/home/ubuntu/EighthArticleExperimentalResults/ImageNet64/author_ckpt/VIRTUAL_imagenet64_labeled.npz --teacher_model_path=/home/ubuntu/EighthArticleExperimentalResults/ImageNet64/author_ckpt/edm_imagenet64_ema.pt --data_dir=/home/ubuntu/dataset/ImageNet/train"
export OMPI_COMM_WORLD_RANK=0
export OMPI_COMM_WORLD_LOCAL_RANK=0
export OMPI_COMM_WORLD_SIZE=8

MODEL_FLAGS="--start_ema=0.999 --save_check_period=1000 --eval_interval=5000 --eval_fid=True --eval_similarity=False --check_dm_performance=False --compute_ema_fids=True --gan_fake_inner_type=model --gan_fake_outer_type=target_model_sg --gan_training=True --g_learning_period=2 --resume_checkpoint=/home/acf15618av/EighthArticleExperimentalResults/CIFAR10/resume_checkpoint/euler_edm_stop_grad_random_17_M_bs_384_from_edm_dsm_1.0/model050000.pt --microbatch=11"
python image_sample.py $MODEL_FLAGS --out_dir /home/fp084243/EighthArticleExperimentalResults/ImageNet64/CD/ --model_path=/home/fp084243/EighthArticleExperimentalResults/ImageNet64/author_ckpt/cd_imagenet64_lpips.pt --training_mode=cd --class_cond=True --eval_num_samples=256 --batch_size=256 --device_id=0 --stochastic_seed=False --save_format=npz --ind_1=5 --ind_2=3 --use_MPI=True --sampler=exact --sampling_steps=1 --eval_seed=0 --train_classes=0




GAIA
ssh gaia
salloc --partition=project142-a100-v2 --ntasks=8 --ntasks-per-node=8 --gpus-per-node=8 --cpus-per-task=32 --time=60 --account=project142

source /etc/profile.d/modules.sh
module load singularity/3.5.3
module load openmpi/3.1.6
singularity run --nv /sample/container/NGC/tensorflow2/nvcr.io-nvidia-tensorflow.22.11-tf2-py3.sif
cd /home/fp084243/EighthArticle/consistency_models-main_ver3
export OMPI_COMM_WORLD_RANK=0
export OMPI_COMM_WORLD_LOCAL_RANK=0
export OMPI_COMM_WORLD_SIZE=8

MODEL_FLAGS="--data_name=imagenet64 --class_cond=True --eval_interval=1000 --save_interval=1000 --num_classes=1000 --eval_batch=250 --eval_fid=True --eval_similarity=False --check_dm_performance=False --log_interval=100"

CUDA_VISIBLE_DEVICES=0 nohup mpiexec -n 1 python image_sample.py $MODEL_FLAGS --class_cond=True --num_classes=1000 --out_dir /home/fp084243/EighthArticleExperimentalResults/ImageNet64/random_samples_to_Jesse --model_path=/home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ema_0.999_038000.pt --training_mode=ctm --class_cond=True --eval_num_samples=6400 --batch_size=800 --device_id=0 --stochastic_seed=True --save_format=npz --ind_1=36 --ind_2=20 --use_MPI=True --sampler=exact --sampling_steps=1 > log.txt 2>&1 &
CUDA_VISIBLE_DEVICES=1 nohup mpiexec -n 1 python image_sample.py $MODEL_FLAGS --class_cond=True --num_classes=1000 --out_dir /home/fp084243/EighthArticleExperimentalResults/ImageNet64/random_samples_to_Jesse --model_path=/home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ema_0.999_038000.pt --training_mode=ctm --class_cond=True --eval_num_samples=6400 --batch_size=800 --device_id=0 --stochastic_seed=True --save_format=npz --ind_1=36 --ind_2=20 --use_MPI=True --sampler=exact --sampling_steps=2 > log.txt 2>&1 &

mpiexec -n 1 python select_image.py --out_dir /home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1 --classifier_path=/home/fp084243/EighthArticleExperimentalResults/ImageNet64/author_ckpt/64x64_classifier.pt --rejection_ratio=0.0001
CUDA_VISIBLE_DEVICES=0 mpiexec -n 1 python3.8 evaluations/evaluator.py /home/fp084243/EighthArticleExperimentalResults/ImageNet64/author_ckpt/VIRTUAL_imagenet64_labeled.npz /home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ctm_exact_sampler_2_steps_034000_itrs_0.999_ema_

python3.8 select_image.py

CUDA_VISIBLE_DEVICES=0 nohup mpiexec -n 1 python image_sample.py $MODEL_FLAGS --class_cond=True --num_classes=1000 --out_dir /home/fp084243/EighthArticleExperimentalResults/ImageNet64/random_samples --model_path=/home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ema_0.999_034000.pt --training_mode=ctm --class_cond=True --eval_num_samples=16 --batch_size=16 --device_id=0 --stochastic_seed=False --save_format=npz --ind_1=36 --ind_2=20 --use_MPI=True --sampler=exact --sampling_steps=1 --train_classes=980 --eval_seed=980 > log.txt 2>&1 &
CUDA_VISIBLE_DEVICES=1 nohup mpiexec -n 1 python image_sample.py $MODEL_FLAGS --class_cond=True --num_classes=1000 --out_dir /home/fp084243/EighthArticleExperimentalResults/ImageNet64/random_samples --model_path=/home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ema_0.999_034000.pt --training_mode=ctm --class_cond=True --eval_num_samples=16 --batch_size=16 --device_id=0 --stochastic_seed=False --save_format=npz --ind_1=36 --ind_2=20 --use_MPI=True --sampler=exact --sampling_steps=2 --train_classes=980 --eval_seed=980 > log.txt 2>&1 &
CUDA_VISIBLE_DEVICES=2 nohup mpiexec -n 1 python image_sample.py $MODEL_FLAGS --class_cond=True --num_classes=1000 --out_dir /home/fp084243/EighthArticleExperimentalResults/ImageNet64/random_samples --model_path=/home/fp084243/EighthArticleExperimentalResults/ImageNet64/author_ckpt/cd_imagenet64_lpips.pt --training_mode=cd --class_cond=True --eval_num_samples=16 --batch_size=16 --device_id=0 --stochastic_seed=False --save_format=npz --ind_1=37 --ind_2=20 --use_MPI=True --sampler=onestep --sampling_steps=1 --train_classes=980 --eval_seed=980 > log.txt 2>&1 &
CUDA_VISIBLE_DEVICES=3 nohup mpiexec -n 1 python image_sample.py $MODEL_FLAGS --class_cond=True --num_classes=1000 --out_dir /home/fp084243/EighthArticleExperimentalResults/ImageNet64/random_samples --model_path=/home/fp084243/EighthArticleExperimentalResults/ImageNet64/author_ckpt/edm_imagenet64_ema.pt --training_mode=edm --class_cond=True --eval_num_samples=16 --batch_size=16 --device_id=0 --stochastic_seed=False --save_format=npz --ind_1=37 --ind_2=20 --use_MPI=True --sampler=heun --sampling_steps=40 --train_classes=980 --eval_seed=980 > log.txt 2>&1 &

CUDA_VISIBLE_DEVICES=4 nohup mpiexec -n 1 python image_sample.py $MODEL_FLAGS --class_cond=True --num_classes=1000 --out_dir /home/fp084243/EighthArticleExperimentalResults/ImageNet64/random_samples --model_path=/home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ema_0.999_034000.pt --training_mode=ctm --class_cond=True --eval_num_samples=16 --batch_size=16 --device_id=0 --stochastic_seed=False --save_format=npz --ind_1=36 --ind_2=20 --use_MPI=True --sampler=exact --sampling_steps=1 --train_classes=973 --eval_seed=973 > log.txt 2>&1 &
CUDA_VISIBLE_DEVICES=5 nohup mpiexec -n 1 python image_sample.py $MODEL_FLAGS --class_cond=True --num_classes=1000 --out_dir /home/fp084243/EighthArticleExperimentalResults/ImageNet64/random_samples --model_path=/home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ema_0.999_034000.pt --training_mode=ctm --class_cond=True --eval_num_samples=16 --batch_size=16 --device_id=0 --stochastic_seed=False --save_format=npz --ind_1=36 --ind_2=20 --use_MPI=True --sampler=exact --sampling_steps=2 --train_classes=973 --eval_seed=973 > log.txt 2>&1 &
CUDA_VISIBLE_DEVICES=6 nohup mpiexec -n 1 python image_sample.py $MODEL_FLAGS --class_cond=True --num_classes=1000 --out_dir /home/fp084243/EighthArticleExperimentalResults/ImageNet64/random_samples --model_path=/home/fp084243/EighthArticleExperimentalResults/ImageNet64/author_ckpt/cd_imagenet64_lpips.pt --training_mode=cd --class_cond=True --eval_num_samples=16 --batch_size=16 --device_id=0 --stochastic_seed=False --save_format=npz --ind_1=37 --ind_2=20 --use_MPI=True --sampler=onestep --sampling_steps=1 --train_classes=973 --eval_seed=973 > log.txt 2>&1 &
CUDA_VISIBLE_DEVICES=7 nohup mpiexec -n 1 python image_sample.py $MODEL_FLAGS --class_cond=True --num_classes=1000 --out_dir /home/fp084243/EighthArticleExperimentalResults/ImageNet64/random_samples --model_path=/home/fp084243/EighthArticleExperimentalResults/ImageNet64/author_ckpt/edm_imagenet64_ema.pt --training_mode=edm --class_cond=True --eval_num_samples=16 --batch_size=16 --device_id=0 --stochastic_seed=False --save_format=npz --ind_1=37 --ind_2=20 --use_MPI=True --sampler=heun --sampling_steps=40 --train_classes=973 --eval_seed=973 > log.txt 2>&1 &


CUDA_VISIBLE_DEVICES=0 nohup mpiexec -n 1 python image_sample.py $MODEL_FLAGS --class_cond=True --num_classes=1000 --out_dir /home/fp084243/EighthArticleExperimentalResults/ImageNet64/random_samples --model_path=/home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ema_0.999_034000.pt --training_mode=ctm --class_cond=True --eval_num_samples=16 --batch_size=16 --device_id=0 --stochastic_seed=False --save_format=npz --ind_1=36 --ind_2=20 --use_MPI=True --sampler=exact --sampling_steps=1 --train_classes=387 --eval_seed=387 > log.txt 2>&1 &
CUDA_VISIBLE_DEVICES=1 nohup mpiexec -n 1 python image_sample.py $MODEL_FLAGS --class_cond=True --num_classes=1000 --out_dir /home/fp084243/EighthArticleExperimentalResults/ImageNet64/random_samples --model_path=/home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ema_0.999_034000.pt --training_mode=ctm --class_cond=True --eval_num_samples=16 --batch_size=16 --device_id=0 --stochastic_seed=False --save_format=npz --ind_1=36 --ind_2=20 --use_MPI=True --sampler=exact --sampling_steps=2 --train_classes=387 --eval_seed=387 > log.txt 2>&1 &
CUDA_VISIBLE_DEVICES=2 nohup mpiexec -n 1 python image_sample.py $MODEL_FLAGS --class_cond=True --num_classes=1000 --out_dir /home/fp084243/EighthArticleExperimentalResults/ImageNet64/random_samples --model_path=/home/fp084243/EighthArticleExperimentalResults/ImageNet64/author_ckpt/cd_imagenet64_lpips.pt --training_mode=cd --class_cond=True --eval_num_samples=16 --batch_size=16 --device_id=0 --stochastic_seed=False --save_format=npz --ind_1=37 --ind_2=20 --use_MPI=True --sampler=onestep --sampling_steps=1 --train_classes=387 --eval_seed=387 > log.txt 2>&1 &
CUDA_VISIBLE_DEVICES=3 nohup mpiexec -n 1 python image_sample.py $MODEL_FLAGS --class_cond=True --num_classes=1000 --out_dir /home/fp084243/EighthArticleExperimentalResults/ImageNet64/random_samples --model_path=/home/fp084243/EighthArticleExperimentalResults/ImageNet64/author_ckpt/edm_imagenet64_ema.pt --training_mode=edm --class_cond=True --eval_num_samples=16 --batch_size=16 --device_id=0 --stochastic_seed=False --save_format=npz --ind_1=37 --ind_2=20 --use_MPI=True --sampler=heun --sampling_steps=40 --train_classes=387 --eval_seed=387 > log.txt 2>&1 &

CUDA_VISIBLE_DEVICES=4 nohup mpiexec -n 1 python image_sample.py $MODEL_FLAGS --class_cond=True --num_classes=1000 --out_dir /home/fp084243/EighthArticleExperimentalResults/ImageNet64/random_samples --model_path=/home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ema_0.999_034000.pt --training_mode=ctm --class_cond=True --eval_num_samples=16 --batch_size=16 --device_id=0 --stochastic_seed=False --save_format=npz --ind_1=36 --ind_2=20 --use_MPI=True --sampler=exact --sampling_steps=1 --train_classes=388 --eval_seed=388 > log.txt 2>&1 &
CUDA_VISIBLE_DEVICES=5 nohup mpiexec -n 1 python image_sample.py $MODEL_FLAGS --class_cond=True --num_classes=1000 --out_dir /home/fp084243/EighthArticleExperimentalResults/ImageNet64/random_samples --model_path=/home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ema_0.999_034000.pt --training_mode=ctm --class_cond=True --eval_num_samples=16 --batch_size=16 --device_id=0 --stochastic_seed=False --save_format=npz --ind_1=36 --ind_2=20 --use_MPI=True --sampler=exact --sampling_steps=2 --train_classes=388 --eval_seed=388 > log.txt 2>&1 &
CUDA_VISIBLE_DEVICES=6 nohup mpiexec -n 1 python image_sample.py $MODEL_FLAGS --class_cond=True --num_classes=1000 --out_dir /home/fp084243/EighthArticleExperimentalResults/ImageNet64/random_samples --model_path=/home/fp084243/EighthArticleExperimentalResults/ImageNet64/author_ckpt/cd_imagenet64_lpips.pt --training_mode=cd --class_cond=True --eval_num_samples=16 --batch_size=16 --device_id=0 --stochastic_seed=False --save_format=npz --ind_1=37 --ind_2=20 --use_MPI=True --sampler=onestep --sampling_steps=1 --train_classes=388 --eval_seed=388 > log.txt 2>&1 &
CUDA_VISIBLE_DEVICES=7 nohup mpiexec -n 1 python image_sample.py $MODEL_FLAGS --class_cond=True --num_classes=1000 --out_dir /home/fp084243/EighthArticleExperimentalResults/ImageNet64/random_samples --model_path=/home/fp084243/EighthArticleExperimentalResults/ImageNet64/author_ckpt/edm_imagenet64_ema.pt --training_mode=edm --class_cond=True --eval_num_samples=16 --batch_size=16 --device_id=0 --stochastic_seed=False --save_format=npz --ind_1=37 --ind_2=20 --use_MPI=True --sampler=heun --sampling_steps=40 --train_classes=388 --eval_seed=388 > log.txt 2>&1 &


CUDA_VISIBLE_DEVICES=0 nohup mpiexec -n 1 python image_sample.py $MODEL_FLAGS --class_cond=True --num_classes=1000 --out_dir /home/fp084243/EighthArticleExperimentalResults/ImageNet64/random_samples --model_path=/home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ema_0.999_034000.pt --training_mode=ctm --class_cond=True --eval_num_samples=16 --batch_size=16 --device_id=0 --stochastic_seed=False --save_format=npz --ind_1=36 --ind_2=20 --use_MPI=True --sampler=exact --sampling_steps=1 --train_classes=89 --eval_seed=89 > log.txt 2>&1 &
CUDA_VISIBLE_DEVICES=1 nohup mpiexec -n 1 python image_sample.py $MODEL_FLAGS --class_cond=True --num_classes=1000 --out_dir /home/fp084243/EighthArticleExperimentalResults/ImageNet64/random_samples --model_path=/home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ema_0.999_034000.pt --training_mode=ctm --class_cond=True --eval_num_samples=16 --batch_size=16 --device_id=0 --stochastic_seed=False --save_format=npz --ind_1=36 --ind_2=20 --use_MPI=True --sampler=exact --sampling_steps=2 --train_classes=89 --eval_seed=89 > log.txt 2>&1 &
CUDA_VISIBLE_DEVICES=2 nohup mpiexec -n 1 python image_sample.py $MODEL_FLAGS --class_cond=True --num_classes=1000 --out_dir /home/fp084243/EighthArticleExperimentalResults/ImageNet64/random_samples --model_path=/home/fp084243/EighthArticleExperimentalResults/ImageNet64/author_ckpt/cd_imagenet64_lpips.pt --training_mode=cd --class_cond=True --eval_num_samples=16 --batch_size=16 --device_id=0 --stochastic_seed=False --save_format=npz --ind_1=37 --ind_2=20 --use_MPI=True --sampler=onestep --sampling_steps=1 --train_classes=89 --eval_seed=89 > log.txt 2>&1 &
CUDA_VISIBLE_DEVICES=3 nohup mpiexec -n 1 python image_sample.py $MODEL_FLAGS --class_cond=True --num_classes=1000 --out_dir /home/fp084243/EighthArticleExperimentalResults/ImageNet64/random_samples --model_path=/home/fp084243/EighthArticleExperimentalResults/ImageNet64/author_ckpt/edm_imagenet64_ema.pt --training_mode=edm --class_cond=True --eval_num_samples=16 --batch_size=16 --device_id=0 --stochastic_seed=False --save_format=npz --ind_1=37 --ind_2=20 --use_MPI=True --sampler=heun --sampling_steps=40 --train_classes=89 --eval_seed=89 > log.txt 2>&1 &

CUDA_VISIBLE_DEVICES=4 nohup mpiexec -n 1 python image_sample.py $MODEL_FLAGS --class_cond=True --num_classes=1000 --out_dir /home/fp084243/EighthArticleExperimentalResults/ImageNet64/random_samples --model_path=/home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ema_0.999_034000.pt --training_mode=ctm --class_cond=True --eval_num_samples=16 --batch_size=16 --device_id=0 --stochastic_seed=False --save_format=npz --ind_1=36 --ind_2=20 --use_MPI=True --sampler=exact --sampling_steps=1 --train_classes=90 --eval_seed=90 > log.txt 2>&1 &
CUDA_VISIBLE_DEVICES=5 nohup mpiexec -n 1 python image_sample.py $MODEL_FLAGS --class_cond=True --num_classes=1000 --out_dir /home/fp084243/EighthArticleExperimentalResults/ImageNet64/random_samples --model_path=/home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ema_0.999_034000.pt --training_mode=ctm --class_cond=True --eval_num_samples=16 --batch_size=16 --device_id=0 --stochastic_seed=False --save_format=npz --ind_1=36 --ind_2=20 --use_MPI=True --sampler=exact --sampling_steps=2 --train_classes=90 --eval_seed=90 > log.txt 2>&1 &
CUDA_VISIBLE_DEVICES=6 nohup mpiexec -n 1 python image_sample.py $MODEL_FLAGS --class_cond=True --num_classes=1000 --out_dir /home/fp084243/EighthArticleExperimentalResults/ImageNet64/random_samples --model_path=/home/fp084243/EighthArticleExperimentalResults/ImageNet64/author_ckpt/cd_imagenet64_lpips.pt --training_mode=cd --class_cond=True --eval_num_samples=16 --batch_size=16 --device_id=0 --stochastic_seed=False --save_format=npz --ind_1=37 --ind_2=20 --use_MPI=True --sampler=onestep --sampling_steps=1 --train_classes=90 --eval_seed=90 > log.txt 2>&1 &
CUDA_VISIBLE_DEVICES=7 nohup mpiexec -n 1 python image_sample.py $MODEL_FLAGS --class_cond=True --num_classes=1000 --out_dir /home/fp084243/EighthArticleExperimentalResults/ImageNet64/random_samples --model_path=/home/fp084243/EighthArticleExperimentalResults/ImageNet64/author_ckpt/edm_imagenet64_ema.pt --training_mode=edm --class_cond=True --eval_num_samples=16 --batch_size=16 --device_id=0 --stochastic_seed=False --save_format=npz --ind_1=37 --ind_2=20 --use_MPI=True --sampler=heun --sampling_steps=40 --train_classes=90 --eval_seed=90 > log.txt 2>&1 &



CUDA_VISIBLE_DEVICES=3 nohup mpiexec -n 1 python image_sample.py $MODEL_FLAGS --class_cond=True --num_classes=1000 --out_dir /home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1 --model_path=/home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ema_0.999_034000.pt --training_mode=ctm --class_cond=True --eval_num_samples=16 --batch_size=16 --device_id=0 --stochastic_seed=True --save_format=npz --ind_1=38 --ind_2=20 --use_MPI=True --sampler=exact --sampling_steps=2 --gamma=0.3 > log.txt 2>&1 &
CUDA_VISIBLE_DEVICES=4 nohup mpiexec -n 1 python image_sample.py $MODEL_FLAGS --class_cond=True --num_classes=1000 --out_dir /home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1 --model_path=/home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ema_0.999_034000.pt --training_mode=ctm --class_cond=True --eval_num_samples=6400 --batch_size=800 --device_id=0 --stochastic_seed=True --save_format=npz --ind_1=39 --ind_2=20 --use_MPI=True --sampler=exact --sampling_steps=2 --gamma=0.3 > log.txt 2>&1 &
CUDA_VISIBLE_DEVICES=5 nohup mpiexec -n 1 python image_sample.py $MODEL_FLAGS --class_cond=True --num_classes=1000 --out_dir /home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1 --model_path=/home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ema_0.999_034000.pt --training_mode=ctm --class_cond=True --eval_num_samples=6400 --batch_size=800 --device_id=0 --stochastic_seed=True --save_format=npz --ind_1=33 --ind_2=20 --use_MPI=True --sampler=exact --sampling_steps=2 --gamma=0.3 > log.txt 2>&1 &
CUDA_VISIBLE_DEVICES=6 nohup mpiexec -n 1 python image_sample.py $MODEL_FLAGS --class_cond=True --num_classes=1000 --out_dir /home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1 --model_path=/home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ema_0.999_034000.pt --training_mode=ctm --class_cond=True --eval_num_samples=6400 --batch_size=800 --device_id=0 --stochastic_seed=True --save_format=npz --ind_1=34 --ind_2=20 --use_MPI=True --sampler=exact --sampling_steps=2 --gamma=0.3 > log.txt 2>&1 &
CUDA_VISIBLE_DEVICES=7 nohup mpiexec -n 1 python image_sample.py $MODEL_FLAGS --class_cond=True --num_classes=1000 --out_dir /home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1 --model_path=/home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ema_0.999_034000.pt --training_mode=ctm --class_cond=True --eval_num_samples=6400 --batch_size=800 --device_id=0 --stochastic_seed=True --save_format=npz --ind_1=35 --ind_2=20 --use_MPI=True --sampler=exact --sampling_steps=2 --gamma=0.3 > log.txt 2>&1 &

singularity run --nv /sample/pytorch/container/nvcr.io-nvidia-pytorch.21.10-py3.sif

singularity run --nv /sample/container/NGC/tensorflow2/nvcr.io-nvidia-tensorflow.22.11-tf2-py3.sif
cd /home/fp084243/EighthArticle/consistency_models-main_ver3
CUDA_VISIBLE_DEVICES=0 mpiexec -n 1 python3.8 evaluations/evaluator.py /home/fp084243/EighthArticleExperimentalResults/ImageNet64/author_ckpt/VIRTUAL_imagenet64_labeled.npz /home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ctm_exact_sampler_1_steps_028000_itrs_0.999_ema_single_npz
CUDA_VISIBLE_DEVICES=0 mpiexec -n 1 python3.8 evaluations/evaluator.py /home/fp084243/EighthArticleExperimentalResults/ImageNet64/author_ckpt/VIRTUAL_imagenet64_labeled.npz /home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ctm_gamma_sampler_2_steps_028000_itrs_0.999_ema__ind1_21_ind2_20
CUDA_VISIBLE_DEVICES=0 mpiexec -n 1 python3.8 evaluations/evaluator.py /home/fp084243/EighthArticleExperimentalResults/ImageNet64/author_ckpt/VIRTUAL_imagenet64_labeled.npz /home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ctm_gamma_sampler_2_steps_028000_itrs_0.999_ema__ind1_22_ind2_20
CUDA_VISIBLE_DEVICES=0 mpiexec -n 1 python3.8 evaluations/evaluator.py /home/fp084243/EighthArticleExperimentalResults/ImageNet64/author_ckpt/VIRTUAL_imagenet64_labeled.npz /home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ctm_gamma_sampler_2_steps_028000_itrs_0.999_ema__ind1_23_ind2_20
CUDA_VISIBLE_DEVICES=0 mpiexec -n 1 python3.8 evaluations/evaluator.py /home/fp084243/EighthArticleExperimentalResults/ImageNet64/author_ckpt/VIRTUAL_imagenet64_labeled.npz /home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ctm_gamma_sampler_2_steps_028000_itrs_0.999_ema__ind1_24_ind2_20
CUDA_VISIBLE_DEVICES=0 mpiexec -n 1 python3.8 evaluations/evaluator.py /home/fp084243/EighthArticleExperimentalResults/ImageNet64/author_ckpt/VIRTUAL_imagenet64_labeled.npz /home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ctm_gamma_sampler_2_steps_028000_itrs_0.999_ema__ind1_25_ind2_20
CUDA_VISIBLE_DEVICES=0 mpiexec -n 1 python3.8 evaluations/evaluator.py /home/fp084243/EighthArticleExperimentalResults/ImageNet64/author_ckpt/VIRTUAL_imagenet64_labeled.npz /home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ctm_gamma_sampler_2_steps_028000_itrs_0.999_ema__ind1_26_ind2_20
CUDA_VISIBLE_DEVICES=0 mpiexec -n 1 python3.8 evaluations/evaluator.py /home/fp084243/EighthArticleExperimentalResults/ImageNet64/author_ckpt/VIRTUAL_imagenet64_labeled.npz /home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ctm_gamma_sampler_2_steps_028000_itrs_0.999_ema__ind1_27_ind2_20
CUDA_VISIBLE_DEVICES=0 mpiexec -n 1 python3.8 evaluations/evaluator.py /home/fp084243/EighthArticleExperimentalResults/ImageNet64/author_ckpt/VIRTUAL_imagenet64_labeled.npz /home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ctm_gamma_sampler_2_steps_028000_itrs_0.999_ema__ind1_28_ind2_20
CUDA_VISIBLE_DEVICES=0 mpiexec -n 1 python3.8 evaluations/evaluator.py /home/fp084243/EighthArticleExperimentalResults/ImageNet64/author_ckpt/VIRTUAL_imagenet64_labeled.npz /home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ctm_gamma_sampler_2_steps_028000_itrs_0.999_ema__ind1_29_ind2_20
CUDA_VISIBLE_DEVICES=0 mpiexec -n 1 python3.8 evaluations/evaluator.py /home/fp084243/EighthArticleExperimentalResults/ImageNet64/author_ckpt/VIRTUAL_imagenet64_labeled.npz /home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ctm_gamma_sampler_2_steps_028000_itrs_0.999_ema__ind1_30_ind2_20
CUDA_VISIBLE_DEVICES=0 mpiexec -n 1 python3.8 evaluations/evaluator.py /home/fp084243/EighthArticleExperimentalResults/ImageNet64/author_ckpt/VIRTUAL_imagenet64_labeled.npz /home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ctm_gamma_sampler_2_steps_028000_itrs_0.999_ema__ind1_31_ind2_20
CUDA_VISIBLE_DEVICES=0 mpiexec -n 1 python3.8 evaluations/evaluator.py /home/fp084243/EighthArticleExperimentalResults/ImageNet64/author_ckpt/VIRTUAL_imagenet64_labeled.npz /home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ctm_gamma_sampler_2_steps_028000_itrs_0.999_ema__ind1_32_ind2_20
CUDA_VISIBLE_DEVICES=0 mpiexec -n 1 python3.8 evaluations/evaluator.py /home/fp084243/EighthArticleExperimentalResults/ImageNet64/author_ckpt/VIRTUAL_imagenet64_labeled.npz /home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ctm_gamma_sampler_2_steps_028000_itrs_0.999_ema__ind1_33_ind2_20
CUDA_VISIBLE_DEVICES=0 mpiexec -n 1 python3.8 evaluations/evaluator.py /home/fp084243/EighthArticleExperimentalResults/ImageNet64/author_ckpt/VIRTUAL_imagenet64_labeled.npz /home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ctm_gamma_sampler_2_steps_028000_itrs_0.999_ema__ind1_34_ind2_20
CUDA_VISIBLE_DEVICES=0 mpiexec -n 1 python3.8 evaluations/evaluator.py /home/fp084243/EighthArticleExperimentalResults/ImageNet64/author_ckpt/VIRTUAL_imagenet64_labeled.npz /home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ctm_gamma_sampler_2_steps_028000_itrs_0.999_ema__ind1_35_ind2_20
CUDA_VISIBLE_DEVICES=0 mpiexec -n 1 python3.8 evaluations/evaluator.py /home/fp084243/EighthArticleExperimentalResults/ImageNet64/author_ckpt/VIRTUAL_imagenet64_labeled.npz /home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ctm_gamma_sampler_2_steps_028000_itrs_0.999_ema__ind1_36_ind2_20
CUDA_VISIBLE_DEVICES=0 mpiexec -n 1 python3.8 evaluations/evaluator.py /home/fp084243/EighthArticleExperimentalResults/ImageNet64/author_ckpt/VIRTUAL_imagenet64_labeled.npz /home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ctm_gamma_sampler_2_steps_028000_itrs_0.999_ema__ind1_37_ind2_20
CUDA_VISIBLE_DEVICES=0 mpiexec -n 1 python3.8 evaluations/evaluator.py /home/fp084243/EighthArticleExperimentalResults/ImageNet64/author_ckpt/VIRTUAL_imagenet64_labeled.npz /home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ctm_gamma_sampler_2_steps_028000_itrs_0.999_ema__ind1_38_ind2_20
CUDA_VISIBLE_DEVICES=0 mpiexec -n 1 python3.8 evaluations/evaluator.py /home/fp084243/EighthArticleExperimentalResults/ImageNet64/author_ckpt/VIRTUAL_imagenet64_labeled.npz /home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ctm_gamma_sampler_2_steps_028000_itrs_0.999_ema__ind1_39_ind2_20

CUDA_VISIBLE_DEVICES=0 mpiexec -n 1 python3.8 evaluations/evaluator.py /home/fp084243/EighthArticleExperimentalResults/ImageNet64/author_ckpt/VIRTUAL_imagenet64_labeled.npz /home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ctm_gamma_sampler_2_steps_028000_itrs_0.999_ema__ind1_21_ind2_21
CUDA_VISIBLE_DEVICES=0 mpiexec -n 1 python3.8 evaluations/evaluator.py /home/fp084243/EighthArticleExperimentalResults/ImageNet64/author_ckpt/VIRTUAL_imagenet64_labeled.npz /home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ctm_gamma_sampler_2_steps_028000_itrs_0.999_ema__ind1_22_ind2_22
CUDA_VISIBLE_DEVICES=0 mpiexec -n 1 python3.8 evaluations/evaluator.py /home/fp084243/EighthArticleExperimentalResults/ImageNet64/author_ckpt/VIRTUAL_imagenet64_labeled.npz /home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ctm_gamma_sampler_2_steps_028000_itrs_0.999_ema__ind1_23_ind2_23
CUDA_VISIBLE_DEVICES=0 mpiexec -n 1 python3.8 evaluations/evaluator.py /home/fp084243/EighthArticleExperimentalResults/ImageNet64/author_ckpt/VIRTUAL_imagenet64_labeled.npz /home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ctm_gamma_sampler_2_steps_028000_itrs_0.999_ema__ind1_5_ind2_4
CUDA_VISIBLE_DEVICES=0 mpiexec -n 1 python3.8 evaluations/evaluator.py /home/fp084243/EighthArticleExperimentalResults/ImageNet64/author_ckpt/VIRTUAL_imagenet64_labeled.npz /home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ctm_gamma_sampler_2_steps_028000_itrs_0.999_ema__ind1_7_ind2_0
CUDA_VISIBLE_DEVICES=0 mpiexec -n 1 python3.8 evaluations/evaluator.py /home/fp084243/EighthArticleExperimentalResults/ImageNet64/author_ckpt/VIRTUAL_imagenet64_labeled.npz /home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ctm_gamma_sampler_2_steps_028000_itrs_0.999_ema__ind1_7_ind2_2
CUDA_VISIBLE_DEVICES=0 mpiexec -n 1 python3.8 evaluations/evaluator.py /home/fp084243/EighthArticleExperimentalResults/ImageNet64/author_ckpt/VIRTUAL_imagenet64_labeled.npz /home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ctm_gamma_sampler_2_steps_028000_itrs_0.999_ema__ind1_7_ind2_4
CUDA_VISIBLE_DEVICES=0 mpiexec -n 1 python3.8 evaluations/evaluator.py /home/fp084243/EighthArticleExperimentalResults/ImageNet64/author_ckpt/VIRTUAL_imagenet64_labeled.npz /home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ctm_gamma_sampler_2_steps_028000_itrs_0.999_ema__ind1_7_ind2_6
CUDA_VISIBLE_DEVICES=0 mpiexec -n 1 python3.8 evaluations/evaluator.py /home/fp084243/EighthArticleExperimentalResults/ImageNet64/author_ckpt/VIRTUAL_imagenet64_labeled.npz /home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ctm_gamma_sampler_2_steps_028000_itrs_0.999_ema__ind1_9_ind2_0
CUDA_VISIBLE_DEVICES=0 mpiexec -n 1 python3.8 evaluations/evaluator.py /home/fp084243/EighthArticleExperimentalResults/ImageNet64/author_ckpt/VIRTUAL_imagenet64_labeled.npz /home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ctm_gamma_sampler_2_steps_028000_itrs_0.999_ema__ind1_9_ind2_2
CUDA_VISIBLE_DEVICES=0 mpiexec -n 1 python3.8 evaluations/evaluator.py /home/fp084243/EighthArticleExperimentalResults/ImageNet64/author_ckpt/VIRTUAL_imagenet64_labeled.npz /home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ctm_gamma_sampler_2_steps_028000_itrs_0.999_ema__ind1_9_ind2_4
CUDA_VISIBLE_DEVICES=0 mpiexec -n 1 python3.8 evaluations/evaluator.py /home/fp084243/EighthArticleExperimentalResults/ImageNet64/author_ckpt/VIRTUAL_imagenet64_labeled.npz /home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ctm_gamma_sampler_2_steps_028000_itrs_0.999_ema__ind1_9_ind2_6
CUDA_VISIBLE_DEVICES=0 mpiexec -n 1 python3.8 evaluations/evaluator.py /home/fp084243/EighthArticleExperimentalResults/ImageNet64/author_ckpt/VIRTUAL_imagenet64_labeled.npz /home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ctm_gamma_sampler_2_steps_028000_itrs_0.999_ema__ind1_9_ind2_8

CD - EDM - CTM+DSM - CTM+DSM+GAN
CUDA_VISIBLE_DEVICES=0 nohup mpiexec -n 1 python image_sample.py $MODEL_FLAGS --class_cond=True --num_classes=1000 --out_dir /home/fp084243/EighthArticleExperimentalResults/ImageNet64/CD/ --model_path=/home/fp084243/EighthArticleExperimentalResults/ImageNet64/author_ckpt/cd_imagenet64_lpips.pt --training_mode=cd --class_cond=True --eval_num_samples=512 --batch_size=512 --device_id=0 --stochastic_seed=False --save_format=npz --ind_1=5 --ind_2=3 --use_MPI=True --sampler=onestep --sampling_steps=1 --eval_seed=0 --train_classes=-2 > log.txt 2>&1 &
CUDA_VISIBLE_DEVICES=1 nohup mpiexec -n 1 python image_sample.py $MODEL_FLAGS --class_cond=True --num_classes=1000 --out_dir /home/fp084243/EighthArticleExperimentalResults/ImageNet64/EDM/ --model_path=/home/fp084243/EighthArticleExperimentalResults/ImageNet64/author_ckpt/edm_imagenet64_ema.pt --training_mode=edm --class_cond=True --eval_num_samples=512 --batch_size=512 --device_id=0 --stochastic_seed=False --save_format=npz --ind_1=5 --ind_2=3 --use_MPI=True --sampler=heun --sampling_steps=40 --eval_seed=0 --train_classes=-2 > log.txt 2>&1 &
CUDA_VISIBLE_DEVICES=2 nohup mpiexec -n 1 python image_sample.py $MODEL_FLAGS --class_cond=True --num_classes=1000 --out_dir /home/fp084243/EighthArticleExperimentalResults/ImageNet64/CTM+DSM/ --model_path=/home/fp084243/EighthArticleExperimentalResults/ImageNet64/CTM/ema_0.999_010000.pt --training_mode=ctm --class_cond=True --eval_num_samples=512 --batch_size=512 --device_id=0 --stochastic_seed=False --save_format=npz --ind_1=5 --ind_2=3 --use_MPI=True --sampler=exact --sampling_steps=1 --eval_seed=0 --train_classes=-2 > log.txt 2>&1 &
CUDA_VISIBLE_DEVICES=3 nohup mpiexec -n 1 python image_sample.py $MODEL_FLAGS --class_cond=True --num_classes=1000 --out_dir /home/fp084243/EighthArticleExperimentalResults/ImageNet64/CTM+DSM+GAN/ --model_path=/home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ema_0.999_025000.pt --training_mode=ctm --class_cond=True --eval_num_samples=512 --batch_size=512 --device_id=0 --stochastic_seed=False --save_format=npz --ind_1=5 --ind_2=3 --use_MPI=True --sampler=exact --sampling_steps=1 --eval_seed=0 --train_classes=-2 > log.txt 2>&1 &
CUDA_VISIBLE_DEVICES=4 nohup mpiexec -n 1 python image_sample.py $MODEL_FLAGS --class_cond=True --num_classes=1000 --out_dir /home/fp084243/EighthArticleExperimentalResults/ImageNet64/CTM+DSM/ --model_path=/home/fp084243/EighthArticleExperimentalResults/ImageNet64/CTM/ema_0.999_010000.pt --training_mode=ctm --class_cond=True --eval_num_samples=512 --batch_size=512 --device_id=0 --stochastic_seed=False --save_format=npz --ind_1=5 --ind_2=3 --use_MPI=True --sampler=exact --sampling_steps=2 --eval_seed=0 --train_classes=-2 > log.txt 2>&1 &
CUDA_VISIBLE_DEVICES=5 nohup mpiexec -n 1 python image_sample.py $MODEL_FLAGS --class_cond=True --num_classes=1000 --out_dir /home/fp084243/EighthArticleExperimentalResults/ImageNet64/CTM+DSM+GAN/ --model_path=/home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ema_0.999_025000.pt --training_mode=ctm --class_cond=True --eval_num_samples=512 --batch_size=512 --device_id=0 --stochastic_seed=False --save_format=npz --ind_1=5 --ind_2=3 --use_MPI=True --sampler=exact --sampling_steps=2 --eval_seed=0 --train_classes=-2 > log.txt 2>&1 &
CUDA_VISIBLE_DEVICES=6 nohup mpiexec -n 1 python image_sample.py $MODEL_FLAGS --class_cond=True --num_classes=1000 --out_dir /home/fp084243/EighthArticleExperimentalResults/ImageNet64/CTM+DSM/ --model_path=/home/fp084243/EighthArticleExperimentalResults/ImageNet64/CTM/ema_0.999_010000.pt --training_mode=ctm --class_cond=True --eval_num_samples=512 --batch_size=512 --device_id=0 --stochastic_seed=False --save_format=npz --ind_1=5 --ind_2=3 --use_MPI=True --sampler=exact --sampling_steps=40 --eval_seed=0 --train_classes=-2 > log.txt 2>&1 &
CUDA_VISIBLE_DEVICES=7 nohup mpiexec -n 1 python image_sample.py $MODEL_FLAGS --class_cond=True --num_classes=1000 --out_dir /home/fp084243/EighthArticleExperimentalResults/ImageNet64/CTM+DSM+GAN/ --model_path=/home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ema_0.999_025000.pt --training_mode=ctm --class_cond=True --eval_num_samples=512 --batch_size=512 --device_id=0 --stochastic_seed=False --save_format=npz --ind_1=5 --ind_2=3 --use_MPI=True --sampler=exact --sampling_steps=40 --eval_seed=0 --train_classes=-2 > log.txt 2>&1 &

CUDA_VISIBLE_DEVICES=0 nohup mpiexec -n 1 python image_sample.py $MODEL_FLAGS --class_cond=True --num_classes=1000 --out_dir /home/fp084243/EighthArticleExperimentalResults/ImageNet64/CD/ --model_path=/home/fp084243/EighthArticleExperimentalResults/ImageNet64/author_ckpt/cd_imagenet64_lpips.pt --training_mode=cd --class_cond=True --eval_num_samples=64 --batch_size=64 --device_id=0 --stochastic_seed=False --save_format=npz --ind_1=5 --ind_2=3 --use_MPI=True --sampler=onestep --sampling_steps=1 --eval_seed=0 --train_classes=0 > log.txt 2>&1 &
CUDA_VISIBLE_DEVICES=1 nohup mpiexec -n 1 python image_sample.py $MODEL_FLAGS --class_cond=True --num_classes=1000 --out_dir /home/fp084243/EighthArticleExperimentalResults/ImageNet64/EDM/ --model_path=/home/fp084243/EighthArticleExperimentalResults/ImageNet64/author_ckpt/edm_imagenet64_ema.pt --training_mode=edm --class_cond=True --eval_num_samples=64 --batch_size=64 --device_id=0 --stochastic_seed=False --save_format=npz --ind_1=5 --ind_2=3 --use_MPI=True --sampler=heun --sampling_steps=40 --eval_seed=0 --train_classes=0 > log.txt 2>&1 &
CUDA_VISIBLE_DEVICES=2 nohup mpiexec -n 1 python image_sample.py $MODEL_FLAGS --class_cond=True --num_classes=1000 --out_dir /home/fp084243/EighthArticleExperimentalResults/ImageNet64/CTM+DSM/ --model_path=/home/fp084243/EighthArticleExperimentalResults/ImageNet64/CTM/ema_0.999_010000.pt --training_mode=ctm --class_cond=True --eval_num_samples=64 --batch_size=64 --device_id=0 --stochastic_seed=False --save_format=npz --ind_1=5 --ind_2=3 --use_MPI=True --sampler=exact --sampling_steps=1 --eval_seed=0 --train_classes=0 > log.txt 2>&1 &
CUDA_VISIBLE_DEVICES=3 nohup mpiexec -n 1 python image_sample.py $MODEL_FLAGS --class_cond=True --num_classes=1000 --out_dir /home/fp084243/EighthArticleExperimentalResults/ImageNet64/CTM+DSM+GAN/ --model_path=/home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ema_0.999_025000.pt --training_mode=ctm --class_cond=True --eval_num_samples=64 --batch_size=64 --device_id=0 --stochastic_seed=False --save_format=npz --ind_1=5 --ind_2=3 --use_MPI=True --sampler=exact --sampling_steps=1 --eval_seed=0 --train_classes=0 > log.txt 2>&1 &
CUDA_VISIBLE_DEVICES=4 nohup mpiexec -n 1 python image_sample.py $MODEL_FLAGS --class_cond=True --num_classes=1000 --out_dir /home/fp084243/EighthArticleExperimentalResults/ImageNet64/CTM+DSM/ --model_path=/home/fp084243/EighthArticleExperimentalResults/ImageNet64/CTM/ema_0.999_010000.pt --training_mode=ctm --class_cond=True --eval_num_samples=64 --batch_size=64 --device_id=0 --stochastic_seed=False --save_format=npz --ind_1=5 --ind_2=3 --use_MPI=True --sampler=exact --sampling_steps=2 --eval_seed=0 --train_classes=0 > log.txt 2>&1 &
CUDA_VISIBLE_DEVICES=5 nohup mpiexec -n 1 python image_sample.py $MODEL_FLAGS --class_cond=True --num_classes=1000 --out_dir /home/fp084243/EighthArticleExperimentalResults/ImageNet64/CTM+DSM+GAN/ --model_path=/home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ema_0.999_025000.pt --training_mode=ctm --class_cond=True --eval_num_samples=64 --batch_size=64 --device_id=0 --stochastic_seed=False --save_format=npz --ind_1=5 --ind_2=3 --use_MPI=True --sampler=exact --sampling_steps=2 --eval_seed=0 --train_classes=0 > log.txt 2>&1 &
CUDA_VISIBLE_DEVICES=6 nohup mpiexec -n 1 python image_sample.py $MODEL_FLAGS --class_cond=True --num_classes=1000 --out_dir /home/fp084243/EighthArticleExperimentalResults/ImageNet64/CTM+DSM/ --model_path=/home/fp084243/EighthArticleExperimentalResults/ImageNet64/CTM/ema_0.999_010000.pt --training_mode=ctm --class_cond=True --eval_num_samples=64 --batch_size=64 --device_id=0 --stochastic_seed=False --save_format=npz --ind_1=5 --ind_2=3 --use_MPI=True --sampler=exact --sampling_steps=40 --eval_seed=0 --train_classes=0 > log.txt 2>&1 &
CUDA_VISIBLE_DEVICES=7 nohup mpiexec -n 1 python image_sample.py $MODEL_FLAGS --class_cond=True --num_classes=1000 --out_dir /home/fp084243/EighthArticleExperimentalResults/ImageNet64/CTM+DSM+GAN/ --model_path=/home/fp084243/EighthArticleExperimentalResults/ImageNet64/GAN/fine_tune_ver3/M20_w1/ema_0.999_025000.pt --training_mode=ctm --class_cond=True --eval_num_samples=64 --batch_size=64 --device_id=0 --stochastic_seed=False --save_format=npz --ind_1=5 --ind_2=3 --use_MPI=True --sampler=exact --sampling_steps=40 --eval_seed=0 --train_classes=0 > log.txt 2>&1 &




python image_sample.py $MODEL_FLAGS $CKPT_FLAGS --out_dir /home/ubuntu/EighthArticleExperimentalResults/ImageNet64/GAN_bs_264/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/ImageNet64/GAN_bs_264/ema_0.999_015000.pt --class_cond=True --batch_size=64 --eval_num_samples=64 --stochastic_seed=False --save_format=png --ind_1=5 --ind_2=3 --use_MPI=True --training_mode=ctm --sampler=gamma_multistep --sampling_steps=2 --classifier_guidance=True --device_id=0

nohup python image_sample.py $MODEL_FLAGS $CKPT_FLAGS --out_dir /home/ubuntu/EighthArticleExperimentalResults/ImageNet64/GAN_bs_264/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/ImageNet64/GAN_bs_264/ema_0.999_015000.pt --class_cond=True --batch_size=800 --eval_num_samples=6400 --stochastic_seed=True --save_format=npz --use_MPI=True --training_mode=ctm --sampler=gamma --sampling_steps=2 --classifier_guidance=True --langevin_steps=5 --target_snr=0.26 --ind_1=20 --ind_2=18 --cg_scale=0. --device_id=0 > log.txt 2>&1 &
nohup python image_sample.py $MODEL_FLAGS $CKPT_FLAGS --out_dir /home/ubuntu/EighthArticleExperimentalResults/ImageNet64/GAN_bs_264/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/ImageNet64/GAN_bs_264/ema_0.999_015000.pt --class_cond=True --batch_size=800 --eval_num_samples=6400 --stochastic_seed=True --save_format=npz --use_MPI=True --training_mode=ctm --sampler=gamma --sampling_steps=2 --classifier_guidance=True --langevin_steps=5 --target_snr=0.26 --ind_1=20 --ind_2=18 --cg_scale=0. --device_id=1 > log.txt 2>&1 &
nohup python image_sample.py $MODEL_FLAGS $CKPT_FLAGS --out_dir /home/ubuntu/EighthArticleExperimentalResults/ImageNet64/GAN_bs_264/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/ImageNet64/GAN_bs_264/ema_0.999_015000.pt --class_cond=True --batch_size=800 --eval_num_samples=6400 --stochastic_seed=True --save_format=npz --use_MPI=True --training_mode=ctm --sampler=gamma --sampling_steps=2 --classifier_guidance=True --langevin_steps=5 --target_snr=0.26 --ind_1=20 --ind_2=18 --cg_scale=0. --device_id=2 > log.txt 2>&1 &
nohup python image_sample.py $MODEL_FLAGS $CKPT_FLAGS --out_dir /home/ubuntu/EighthArticleExperimentalResults/ImageNet64/GAN_bs_264/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/ImageNet64/GAN_bs_264/ema_0.999_015000.pt --class_cond=True --batch_size=800 --eval_num_samples=6400 --stochastic_seed=True --save_format=npz --use_MPI=True --training_mode=ctm --sampler=gamma --sampling_steps=2 --classifier_guidance=True --langevin_steps=5 --target_snr=0.26 --ind_1=20 --ind_2=18 --cg_scale=0. --device_id=3 > log.txt 2>&1 &
nohup python image_sample.py $MODEL_FLAGS $CKPT_FLAGS --out_dir /home/ubuntu/EighthArticleExperimentalResults/ImageNet64/GAN_bs_264/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/ImageNet64/GAN_bs_264/ema_0.999_015000.pt --class_cond=True --batch_size=800 --eval_num_samples=6400 --stochastic_seed=True --save_format=npz --use_MPI=True --training_mode=ctm --sampler=gamma --sampling_steps=2 --classifier_guidance=True --langevin_steps=5 --target_snr=0.26 --ind_1=20 --ind_2=18 --cg_scale=0. --device_id=4 > log.txt 2>&1 &
nohup python image_sample.py $MODEL_FLAGS $CKPT_FLAGS --out_dir /home/ubuntu/EighthArticleExperimentalResults/ImageNet64/GAN_bs_264/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/ImageNet64/GAN_bs_264/ema_0.999_015000.pt --class_cond=True --batch_size=800 --eval_num_samples=6400 --stochastic_seed=True --save_format=npz --use_MPI=True --training_mode=ctm --sampler=gamma --sampling_steps=2 --classifier_guidance=True --langevin_steps=5 --target_snr=0.26 --ind_1=20 --ind_2=18 --cg_scale=0. --device_id=5 > log.txt 2>&1 &
nohup python image_sample.py $MODEL_FLAGS $CKPT_FLAGS --out_dir /home/ubuntu/EighthArticleExperimentalResults/ImageNet64/GAN_bs_264/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/ImageNet64/GAN_bs_264/ema_0.999_015000.pt --class_cond=True --batch_size=800 --eval_num_samples=6400 --stochastic_seed=True --save_format=npz --use_MPI=True --training_mode=ctm --sampler=gamma --sampling_steps=2 --classifier_guidance=True --langevin_steps=5 --target_snr=0.26 --ind_1=20 --ind_2=18 --cg_scale=0. --device_id=6 > log.txt 2>&1 &
nohup python image_sample.py $MODEL_FLAGS $CKPT_FLAGS --out_dir /home/ubuntu/EighthArticleExperimentalResults/ImageNet64/GAN_bs_264/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/ImageNet64/GAN_bs_264/ema_0.999_015000.pt --class_cond=True --batch_size=800 --eval_num_samples=6400 --stochastic_seed=True --save_format=npz --use_MPI=True --training_mode=ctm --sampler=gamma --sampling_steps=2 --classifier_guidance=True --langevin_steps=5 --target_snr=0.26 --ind_1=20 --ind_2=18 --cg_scale=0. --device_id=7 > log.txt 2>&1 &

nohup python image_sample.py $MODEL_FLAGS $CKPT_FLAGS --out_dir /home/ubuntu/EighthArticleExperimentalResults/ImageNet64/GAN_bs_264/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/ImageNet64/GAN_bs_264/ema_0.999_015000.pt --class_cond=True --batch_size=125 --eval_num_samples=1250 --stochastic_seed=True --save_format=npz --use_MPI=True --training_mode=ctm --sampler=gamma --sampling_steps=2 --classifier_guidance=True --langevin_steps=5 --target_snr=0.26 --ind_1=34 --ind_2=34 --cg_scale=2.0 --device_id=0 > log.txt 2>&1 &
nohup python image_sample.py $MODEL_FLAGS $CKPT_FLAGS --out_dir /home/ubuntu/EighthArticleExperimentalResults/ImageNet64/GAN_bs_264/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/ImageNet64/GAN_bs_264/ema_0.999_015000.pt --class_cond=True --batch_size=125 --eval_num_samples=1250 --stochastic_seed=True --save_format=npz --use_MPI=True --training_mode=ctm --sampler=gamma --sampling_steps=2 --classifier_guidance=True --langevin_steps=5 --target_snr=0.26 --ind_1=34 --ind_2=34 --cg_scale=2.0 --device_id=1 > log.txt 2>&1 &
nohup python image_sample.py $MODEL_FLAGS $CKPT_FLAGS --out_dir /home/ubuntu/EighthArticleExperimentalResults/ImageNet64/GAN_bs_264/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/ImageNet64/GAN_bs_264/ema_0.999_015000.pt --class_cond=True --batch_size=125 --eval_num_samples=1250 --stochastic_seed=True --save_format=npz --use_MPI=True --training_mode=ctm --sampler=gamma --sampling_steps=2 --classifier_guidance=True --langevin_steps=5 --target_snr=0.26 --ind_1=34 --ind_2=34 --cg_scale=2.0 --device_id=2 > log.txt 2>&1 &
nohup python image_sample.py $MODEL_FLAGS $CKPT_FLAGS --out_dir /home/ubuntu/EighthArticleExperimentalResults/ImageNet64/GAN_bs_264/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/ImageNet64/GAN_bs_264/ema_0.999_015000.pt --class_cond=True --batch_size=125 --eval_num_samples=1250 --stochastic_seed=True --save_format=npz --use_MPI=True --training_mode=ctm --sampler=gamma --sampling_steps=2 --classifier_guidance=True --langevin_steps=5 --target_snr=0.26 --ind_1=34 --ind_2=34 --cg_scale=2.0 --device_id=3 > log.txt 2>&1 &
nohup python image_sample.py $MODEL_FLAGS $CKPT_FLAGS --out_dir /home/ubuntu/EighthArticleExperimentalResults/ImageNet64/GAN_bs_264/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/ImageNet64/GAN_bs_264/ema_0.999_015000.pt --class_cond=True --batch_size=125 --eval_num_samples=1250 --stochastic_seed=True --save_format=npz --use_MPI=True --training_mode=ctm --sampler=gamma --sampling_steps=2 --classifier_guidance=True --langevin_steps=5 --target_snr=0.26 --ind_1=34 --ind_2=34 --cg_scale=2.0 --device_id=4 > log.txt 2>&1 &
nohup python image_sample.py $MODEL_FLAGS $CKPT_FLAGS --out_dir /home/ubuntu/EighthArticleExperimentalResults/ImageNet64/GAN_bs_264/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/ImageNet64/GAN_bs_264/ema_0.999_015000.pt --class_cond=True --batch_size=125 --eval_num_samples=1250 --stochastic_seed=True --save_format=npz --use_MPI=True --training_mode=ctm --sampler=gamma --sampling_steps=2 --classifier_guidance=True --langevin_steps=5 --target_snr=0.26 --ind_1=34 --ind_2=34 --cg_scale=2.0 --device_id=5 > log.txt 2>&1 &
nohup python image_sample.py $MODEL_FLAGS $CKPT_FLAGS --out_dir /home/ubuntu/EighthArticleExperimentalResults/ImageNet64/GAN_bs_264/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/ImageNet64/GAN_bs_264/ema_0.999_015000.pt --class_cond=True --batch_size=125 --eval_num_samples=1250 --stochastic_seed=True --save_format=npz --use_MPI=True --training_mode=ctm --sampler=gamma --sampling_steps=2 --classifier_guidance=True --langevin_steps=5 --target_snr=0.26 --ind_1=34 --ind_2=34 --cg_scale=2.0 --device_id=6 > log.txt 2>&1 &
nohup python image_sample.py $MODEL_FLAGS $CKPT_FLAGS --out_dir /home/ubuntu/EighthArticleExperimentalResults/ImageNet64/GAN_bs_264/ --model_path=/home/ubuntu/EighthArticleExperimentalResults/ImageNet64/GAN_bs_264/ema_0.999_015000.pt --class_cond=True --batch_size=125 --eval_num_samples=1250 --stochastic_seed=True --save_format=npz --use_MPI=True --training_mode=ctm --sampler=gamma --sampling_steps=2 --classifier_guidance=True --langevin_steps=5 --target_snr=0.26 --ind_1=34 --ind_2=34 --cg_scale=2.0 --device_id=7 > log.txt 2>&1 &



CUDA_VISIBLE_DEVICES=0 python evaluations/evaluator.py /home/ubuntu/EighthArticleExperimentalResults/ImageNet64/author_ckpt/VIRTUAL_imagenet64_labeled.npz /home/ubuntu/EighthArticleExperimentalResults/ImageNet64/GAN_bs_264/ctm_gamma_sampler_2_steps_015000_itrs_0.999_ema__ind1_20_ind2_4_cg_0.0_langevin_5_snr_0.26
CUDA_VISIBLE_DEVICES=1 python evaluations/evaluator.py /home/ubuntu/EighthArticleExperimentalResults/ImageNet64/author_ckpt/VIRTUAL_imagenet64_labeled.npz /home/ubuntu/EighthArticleExperimentalResults/ImageNet64/GAN_bs_264/ctm_gamma_sampler_2_steps_015000_itrs_0.999_ema__ind1_20_ind2_6_cg_0.0_langevin_5_snr_0.26
CUDA_VISIBLE_DEVICES=2 python evaluations/evaluator.py /home/ubuntu/EighthArticleExperimentalResults/ImageNet64/author_ckpt/VIRTUAL_imagenet64_labeled.npz /home/ubuntu/EighthArticleExperimentalResults/ImageNet64/GAN_bs_264/ctm_gamma_sampler_2_steps_015000_itrs_0.999_ema__ind1_20_ind2_8_cg_0.0_langevin_5_snr_0.26
CUDA_VISIBLE_DEVICES=3 python evaluations/evaluator.py /home/ubuntu/EighthArticleExperimentalResults/ImageNet64/author_ckpt/VIRTUAL_imagenet64_labeled.npz /home/ubuntu/EighthArticleExperimentalResults/ImageNet64/GAN_bs_264/ctm_gamma_sampler_2_steps_015000_itrs_0.999_ema__ind1_20_ind2_10_cg_0.0_langevin_5_snr_0.26
CUDA_VISIBLE_DEVICES=4 python evaluations/evaluator.py /home/ubuntu/EighthArticleExperimentalResults/ImageNet64/author_ckpt/VIRTUAL_imagenet64_labeled.npz /home/ubuntu/EighthArticleExperimentalResults/ImageNet64/GAN_bs_264/ctm_gamma_sampler_2_steps_015000_itrs_0.999_ema__ind1_20_ind2_12_cg_0.0_langevin_5_snr_0.26
CUDA_VISIBLE_DEVICES=5 python evaluations/evaluator.py /home/ubuntu/EighthArticleExperimentalResults/ImageNet64/author_ckpt/VIRTUAL_imagenet64_labeled.npz /home/ubuntu/EighthArticleExperimentalResults/ImageNet64/GAN_bs_264/ctm_gamma_sampler_2_steps_015000_itrs_0.999_ema__ind1_20_ind2_14_cg_0.0_langevin_5_snr_0.26
CUDA_VISIBLE_DEVICES=6 python evaluations/evaluator.py /home/ubuntu/EighthArticleExperimentalResults/ImageNet64/author_ckpt/VIRTUAL_imagenet64_labeled.npz /home/ubuntu/EighthArticleExperimentalResults/ImageNet64/GAN_bs_264/ctm_gamma_sampler_2_steps_015000_itrs_0.999_ema__ind1_20_ind2_16_cg_0.0_langevin_5_snr_0.26
CUDA_VISIBLE_DEVICES=7 python evaluations/evaluator.py /home/ubuntu/EighthArticleExperimentalResults/ImageNet64/author_ckpt/VIRTUAL_imagenet64_labeled.npz /home/ubuntu/EighthArticleExperimentalResults/ImageNet64/GAN_bs_264/ctm_gamma_sampler_2_steps_015000_itrs_0.999_ema__ind1_20_ind2_18_cg_0.0_langevin_5_snr_0.26

CUDA_VISIBLE_DEVICES=0 python evaluations/evaluator.py /home/ubuntu/EighthArticleExperimentalResults/ImageNet64/author_ckpt/VIRTUAL_imagenet64_labeled.npz /home/ubuntu/EighthArticleExperimentalResults/ImageNet64/GAN_bs_264/ctm_gamma_sampler_2_steps_015000_itrs_0.999_ema__ind1_20_ind2_18_cg_0.1_langevin_5_snr_0.26

CUDA_VISIBLE_DEVICES=0 python evaluations/evaluator.py /home/ubuntu/EighthArticleExperimentalResults/ImageNet64/author_ckpt/VIRTUAL_imagenet64_labeled.npz /home/ubuntu/EighthArticleExperimentalResults/ImageNet64/GAN_bs_264/ctm_gamma_sampler_2_steps_015000_itrs_0.999_ema__ind1_30_ind2_24_cg_0.0_langevin_5_snr_0.26
CUDA_VISIBLE_DEVICES=1 python evaluations/evaluator.py /home/ubuntu/EighthArticleExperimentalResults/ImageNet64/author_ckpt/VIRTUAL_imagenet64_labeled.npz /home/ubuntu/EighthArticleExperimentalResults/ImageNet64/GAN_bs_264/ctm_gamma_sampler_2_steps_015000_itrs_0.999_ema__ind1_30_ind2_26_cg_0.0_langevin_5_snr_0.26
CUDA_VISIBLE_DEVICES=2 python evaluations/evaluator.py /home/ubuntu/EighthArticleExperimentalResults/ImageNet64/author_ckpt/VIRTUAL_imagenet64_labeled.npz /home/ubuntu/EighthArticleExperimentalResults/ImageNet64/GAN_bs_264/ctm_gamma_sampler_2_steps_015000_itrs_0.999_ema__ind1_30_ind2_28_cg_0.0_langevin_5_snr_0.26
CUDA_VISIBLE_DEVICES=3 python evaluations/evaluator.py /home/ubuntu/EighthArticleExperimentalResults/ImageNet64/author_ckpt/VIRTUAL_imagenet64_labeled.npz /home/ubuntu/EighthArticleExperimentalResults/ImageNet64/GAN_bs_264/ctm_gamma_sampler_2_steps_015000_itrs_0.999_ema__ind1_30_ind2_22_cg_0.0_langevin_5_snr_0.26
CUDA_VISIBLE_DEVICES=4 python evaluations/evaluator.py /home/ubuntu/EighthArticleExperimentalResults/ImageNet64/author_ckpt/VIRTUAL_imagenet64_labeled.npz /home/ubuntu/EighthArticleExperimentalResults/ImageNet64/GAN_bs_264/ctm_gamma_sampler_2_steps_015000_itrs_0.999_ema__ind1_30_ind2_20_cg_0.0_langevin_5_snr_0.26
CUDA_VISIBLE_DEVICES=5 python evaluations/evaluator.py /home/ubuntu/EighthArticleExperimentalResults/ImageNet64/author_ckpt/VIRTUAL_imagenet64_labeled.npz /home/ubuntu/EighthArticleExperimentalResults/ImageNet64/GAN_bs_264/ctm_gamma_sampler_2_steps_015000_itrs_0.999_ema__ind1_30_ind2_30_cg_0.0_langevin_5_snr_0.26
CUDA_VISIBLE_DEVICES=6 python evaluations/evaluator.py /home/ubuntu/EighthArticleExperimentalResults/ImageNet64/author_ckpt/VIRTUAL_imagenet64_labeled.npz /home/ubuntu/EighthArticleExperimentalResults/ImageNet64/GAN_bs_264/ctm_gamma_sampler_2_steps_015000_itrs_0.999_ema__ind1_32_ind2_32_cg_0.0_langevin_5_snr_0.26
CUDA_VISIBLE_DEVICES=7 python evaluations/evaluator.py /home/ubuntu/EighthArticleExperimentalResults/ImageNet64/author_ckpt/VIRTUAL_imagenet64_labeled.npz /home/ubuntu/EighthArticleExperimentalResults/ImageNet64/GAN_bs_264/ctm_gamma_sampler_2_steps_015000_itrs_0.999_ema__ind1_20_ind2_18_cg_0.0_langevin_5_snr_0.26